# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd9517a54a323802b4debe4903d392459701b4770aaed25aea513ab26a6f14c84dc934cd67a4eb6a1fbc43db8382117f2c3a9ecd1211e93bc5fcdb74f42fbe7d

test:
  secret_key_base: 73f044a80c1adb258ed6e0138188744d9465263592360edb3e13f898e0f61a5d89bd9a43319823ef95e3dee15c804e12d3a29728fc0ab33ce6b8c9728be19770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
