# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe109da431616d318cf80078eaec0e5d521e090c67b4fe9d65327915a85e5191c23d918dc620e0826f683c4220095c53847ecf1251accfd90d101f922e884a26

test:
  secret_key_base: b8cc922788885b600b7a901177f306fa5de4404675fd14fbbaeed05ef7e43680b29317e9e2e4ce4b3100dde0dd6f58f9ff8553c4b6eba12f8814d3f92a03ca37

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: b8cc922788885b600b7a901177f306fa5de4404675fd14fbbaeed05ef7e43680b29317e9e2e4ce4b3100dde0dd6f58f9ff8553c4b6eba12f8814d3f92a03ca37